[package]
name = "rpi-cube"
version = "0.1.0"
edition = "2021"

[dependencies]
flexi_logger = "0.29.0"
libc = "0.2.158"
log = "0.4.22"
memmap2 = "0.9.5"
once_cell = "1.19.0"
rand = "0.8.5"
rpi-mailbox = { path = "./rpi-mailbox" }
